services:
  mongodb:
    image: mongo:latest
    container_name: local_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
