import { Router, Request, Response } from 'express'

export const router = Router()

router.post('/', async (req: Request, res: Response) => {
  if (!req.body?.text) {
    res.status(400).send('Text is required')
    return
  }

  const snippet = {
    text: req.body.text,
    summary: 'Mocked summary not generated by AI'
  }

  res.status(201).send(snippet)
})

router.get('/', (req: Request, res: Response) => {
  res.send('Get to snippets')
})

router.get('/:id', (req: Request, res: Response) => {
  res.send('Get to snippets/abc-123')
})
