import { Router, Request, Response } from 'express'
import { Snippet } from '../models/snippet'

export const router = Router()

router.post('/', async (req: Request, res: Response) => {
  if (!req.body?.text) {
    res.status(400).send('Text is required')
    return
  }

  const snippet = new Snippet({
    text: req.body.text,
    summary: 'Mocked summary not generated by AI'
  })

  await snippet.save()

  res.status(201).send(snippet)
})

router.get('/', async (req: Request, res: Response) => {
  const snippets = await Snippet.find({})
  res.send(snippets)
})

router.get('/:id', async (req: Request, res: Response) => {
  try {
    const snippet = await Snippet.findById(req.params.id)
    if (!snippet) {
      res.status(404).send('Snippet not found')
      return
    }
    res.send(snippet)
  } catch (err) {
    res.status(400).send('Invalid snippet ID')
  }
})
